### ISSUE TITLE
autoLoad.php が存在しなく起動しない

### ISSUE THREAD

**Issue by NekoFuwa1739** [DaisukeDaisuke/pmmpDiscordBot#4]
`[Server thread/ERROR]: [pmmpDiscordBot] phar:///home/kuroneko5159/PMMP-Main/plugins/pmmpDiscordBot.phar/vendor/autoload.php ファ イルに関しましては存在致しません為、discordbotを起動することは出来ません。`
と表示されてしまい、起動できません。
サーバーAPIは4.0です。
makepharを使ってpmmpDiscordbot.pharにもしてあります。どうしたらいいでしょうか

**Comment by DaisukeDaisuke** [comment]
ご報告ありがとうございます。
makepharを実行する前に、`composer.json`と同じディレクトリにて`composer install`コマンドを実行し、依存関係であるdiscordphpのインストール、venderフォルダを生成する必要性は存在します。
## composer インストール方法と、依存関係のインストール方法
### Windows インストーラー
https://getcomposer.org/Composer-Setup.exe
```
cd pmmpDiscordBot
composer install --no-dev
```
### phar
https://getcomposer.org/composer-stable.phar
php = pmmp binにある`php.exe`
```
cd pmmpDiscordBot
php composer.phar install --no-dev
```
## Linux
phar版 composerを使用します(`sudo apt install composer`でもインストール可能、しかし何かと不都合多め)
php = pmmp binに存在する`php`
```
sudo apt install unzip
wget https://github.com/DaisukeDaisuke/pmmpDiscordBot/archive/refs/heads/master.zip

unzip master.zip
cd pmmpDiscordBot-master
wget https://getcomposer.org/composer-stable.phar

php composer-stable.phar install --no-dev
```

## pmmp bin(pmmp向けphp)のダウンロードサイト
https://jenkins.pmmp.io/job/PHP-8.0-Aggregate/

**Comment by NekoFuwa1739** [comment]
`php composer-stable.phar install --no-dev`
を実行すると
`kuroneko5159@kuroneko5159-vhp:~/PMMP-Main/pmmpDiscordBot-master$ php composer-stable.phar install --no-dev
PHP Warning:  PHP Startup: ^(text/|application/xhtml\+xml) (offset=0): unrecognised compile-time option bit(s) in Unknown on line 0
PHP Fatal error:  Uncaught ErrorException: preg_match_all(): Compilation failed: unrecognised compile-time option bit(s) at offset 0 in phar:///home/kuroneko5159/PMMP-Main/pmmpDiscordBot-master/composer-stable.phar/vendor/symfony/console/Formatter/OutputFormatter.php:152
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle()
#1 phar:///home/kuroneko5159/PMMP-Main/pmmpDiscordBot-master/composer-stable.phar/vendor/symfony/console/Formatter/OutputFormatter.php(152): preg_match_all()
#2 phar:///home/kuroneko5159/PMMP-Main/pmmpDiscordBot-master/composer-stable.phar/vendor/symfony/console/Formatter/OutputFormatter.php(135): Symfony\Component\Console\Formatter\OutputFormatter->formatAndWrap()
#3 phar:///home/kuroneko5159/PMMP-Main/pmmpDiscordBot-master/composer-stable.phar/vendor/symfony/console/Output/Output.php(157): Symfony\Component\Console\Formatter\OutputFormatter->format()
#4 phar:///home/kuroneko5159/PMMP-Main/pmmpDiscordBot-master/composer-stable.phar/vendor/symfony/console/Output/Output.php(132): Symfony\Component\Console\Output\Output->write()
#5 phar:///home/kuroneko5159/PMMP-Main/pmmpDiscordBot-master/composer-stable.phar/vendor/symfony/console/Application.php(836): Symfony\Component\Console\Output\Output->writeln()
#6 phar:///home/kuroneko5159/PMMP-Main/pmmpDiscordBot-master/composer-stable.phar/vendor/symfony/console/Application.php(154): Symfony\Component\Console\Application->renderThrowable()
#7 phar:///home/kuroneko5159/PMMP-Main/pmmpDiscordBot-master/composer-stable.phar/vendor/symfony/console/Application.php(177): Symfony\Component\Console\Application->Symfony\Component\Console\{closure}()
#8 phar:///home/kuroneko5159/PMMP-Main/pmmpDiscordBot-master/composer-stable.phar/src/Composer/Console/Application.php(138): Symfony\Component\Console\Application->run()
#9 phar:///home/kuroneko5159/PMMP-Main/pmmpDiscordBot-master/composer-stable.phar/bin/composer(88): Composer\Console\Application->run()
#10 /home/kuroneko5159/PMMP-Main/pmmpDiscordBot-master/composer-stable.phar(29): require('...')
#11 {main}
  thrown in phar:///home/kuroneko5159/PMMP-Main/pmmpDiscordBot-master/composer-stable.phar/vendor/symfony/console/Formatter/OutputFormatter.php on line 152
Fatal error: Uncaught ErrorException: preg_match_all(): Compilation failed: unrecognised compile-time option bit(s) at offset 0 in phar:///home/kuroneko5159/PMMP-Main/pmmpDiscordBot-master/composer-stable.phar/vendor/symfony/console/Formatter/OutputFormatter.php:152
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle()
#1 phar:///home/kuroneko5159/PMMP-Main/pmmpDiscordBot-master/composer-stable.phar/vendor/symfony/console/Formatter/OutputFormatter.php(152): preg_match_all()
#2 phar:///home/kuroneko5159/PMMP-Main/pmmpDiscordBot-master/composer-stable.phar/vendor/symfony/console/Formatter/OutputFormatter.php(135): Symfony\Component\Console\Formatter\OutputFormatter->formatAndWrap()
#3 phar:///home/kuroneko5159/PMMP-Main/pmmpDiscordBot-master/composer-stable.phar/vendor/symfony/console/Output/Output.php(157): Symfony\Component\Console\Formatter\OutputFormatter->format()
#4 phar:///home/kuroneko5159/PMMP-Main/pmmpDiscordBot-master/composer-stable.phar/vendor/symfony/console/Output/Output.php(132): Symfony\Component\Console\Output\Output->write()
#5 phar:///home/kuroneko5159/PMMP-Main/pmmpDiscordBot-master/composer-stable.phar/vendor/symfony/console/Application.php(836): Symfony\Component\Console\Output\Output->writeln()
#6 phar:///home/kuroneko5159/PMMP-Main/pmmpDiscordBot-master/composer-stable.phar/vendor/symfony/console/Application.php(154): Symfony\Component\Console\Application->renderThrowable()
#7 phar:///home/kuroneko5159/PMMP-Main/pmmpDiscordBot-master/composer-stable.phar/vendor/symfony/console/Application.php(177): Symfony\Component\Console\Application->Symfony\Component\Console\{closure}()
#8 phar:///home/kuroneko5159/PMMP-Main/pmmpDiscordBot-master/composer-stable.phar/src/Composer/Console/Application.php(138): Symfony\Component\Console\Application->run()
#9 phar:///home/kuroneko5159/PMMP-Main/pmmpDiscordBot-master/composer-stable.phar/bin/composer(88): Composer\Console\Application->run()
#10 /home/kuroneko5159/PMMP-Main/pmmpDiscordBot-master/composer-stable.phar(29): require('...')
#11 {main}
  thrown in phar:///home/kuroneko5159/PMMP-Main/pmmpDiscordBot-master/composer-stable.phar/vendor/symfony/console/Formatter/OutputFormatter.php on line 152`
というエラーが出てしまいます。

**Comment by DaisukeDaisuke** [comment]
おそらく、phpのバージョン新しい/古すぎる事によるエラーと推測します。
php7.4/php 8.0系列またはpmmp向けのbinでの実行お願いします！
```
stackoverflow
下記の質問の場合、PCREのバージョン古すぎる事により、同じエラー発生しています。
PHP 5.4 after-install: preg_match(): Compilation failed: unknown option bit(s) set at offset 0
https://stackoverflow.com/questions/10338234/php-5-4-after-install-preg-match-compilation-failed-unknown-option-bits-s
```
下記の組み合わせにて動作確認済み
```
win10、php 8.0.21、composer 2.4.1
ubuntu 22、php 8.0.21、composer 2.4.1
```
### phpのバージョン確認方法
```
php -v
```
```
PHP 8.0.21 (cli) (built: Aug 19 2022 18:09:18) ( ZTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.21, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.21, Copyright (c), by Zend Technologies
```
### pmp binのダウンロード元
https://jenkins.pmmp.io/job/PHP-8.0-Aggregate/
```
bin/php7/bin/php composer-stable.phar install --no-dev
```
下記のopcache読み込みエラーに関して、動作に支障を及ぼさない警告文であるため、放置にて問題ございません。
```
Warning: Failed loading Zend extension 'opcache.so' (tried: /home/runner/work/php-build-scripts/php-build-scripts/bin/php7/lib/php/extensions/no-debug-zts-20200930/opcache.so (/home/runner/work/php-build-scripts/php-build-scripts/bin/php7/lib/php/extensions/no-debug-zts-20200930/opcache.so: cannot open shared object file: No such file or directory), /home/runner/work/php-build-scripts/php-build-scripts/bin/php7/lib/php/extensions/no-debug-zts-20200930/opcache.so.so (/home/runner/work/php-build-scripts/php-build-scripts/bin/php7/lib/php/extensions/no-debug-zts-20200930/opcache.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

Warning: Failed loading Zend extension 'xdebug.so' (tried: /home/runner/work/php-build-scripts/php-build-scripts/bin/php7/lib/php/extensions/no-debug-zts-20200930/xdebug.so (/home/runner/work/php-build-scripts/php-build-scripts/bin/php7/lib/php/extensions/no-debug-zts-20200930/xdebug.so: cannot open shared object file: No such file or directory), /home/runner/work/php-build-scripts/php-build-scripts/bin/php7/lib/php/extensions/no-debug-zts-20200930/xdebug.so.so (/home/runner/work/php-build-scripts/php-build-scripts/bin/php7/lib/php/extensions/no-debug-zts-20200930/xdebug.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

```
https://doc.pmmp.io/en/rtfd/faq/installation/opcache.so.html

**Comment by NekoFuwa1739** [comment]
ありがとうございました！
