### ISSUE TITLE
Discord内から送信できない

### ISSUE THREAD

**Issue by NekoFuwa1739** [DaisukeDaisuke/pmmpDiscordBot#5]
Discord内からコマンドやメッセージを送信しても反応がありません。
`string(0) "" ""`
とコンソールに表示されています

**Comment by DaisukeDaisuke** [comment]
メッセージ送信イベントを取得したい場合「MESSAGE CONTENT INTENT」インテント必須です。
discord developer portal
https://discord.com/developers/applications

↓下記の画像内、一番下にあるトグルの有効化お願いします！
![img](https://user-images.githubusercontent.com/17798680/192128890-edf4c258-ee4a-47b0-8939-98b6319bff04.jpg)

**Comment by NekoFuwa1739** [comment]
ありがとうございます！おかげさまで出来ました！
